question_data = [
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Igneous rocks are formed by excessive heat and pressure.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A group of islands is called an &#039;archipelago&#039;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Spitfire originated from a racing plane.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Politics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Kangaroos keep food in their pouches next to their children.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The logo for Snapchat is a Bell.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A universal set, or a set that contains all sets, exists.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States was a member of the League of Nations.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A bear does NOT defecate during hibernation. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Mythology",
        "type": "boolean",
        "difficulty": "easy",
        "question": "According to Greek Mythology, Zeus can control lightning.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Ottawa is the capital of Canada.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "There are no deserts in Europe.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Geography",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Toronto is the capital city of the North American country of Canada.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Animals",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A flock of crows is known as a homicide.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Mythology",
        "type": "boolean",
        "difficulty": "easy",
        "question": "According to Greek Mythology, Atlas was an Olympian God.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Klingons express emotion in art through opera and poetry.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Television",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Japanese Anime & Manga",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science & Nature",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Psychology is the science of behavior and mind.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Film",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "An isosceles triangle has two sides of equal length as opposed to three.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A pasodoble is a type of Italian pasta sauce.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Science: Computers",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Each piece in Tetris is called a tetris.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Books",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Jingle Bells was originally meant for Thanksgiving",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Ping-Pong originated in England",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The shotgun appears in every numbered Resident Evil game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
]
